-- ==============================================================================
-- Supabase PostgreSQL Database Schema
-- Hackathon & Tech Event Tracker
-- ==============================================================================

-- 1. Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Create Hackathons Table
CREATE TABLE IF NOT EXISTS public.hackathons (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'hackathon',
    description TEXT DEFAULT '',
    organizer TEXT DEFAULT '',
    category TEXT NOT NULL DEFAULT 'Web3',
    mode TEXT NOT NULL DEFAULT 'Online',
    location TEXT DEFAULT '',
    city TEXT DEFAULT '',
    country TEXT DEFAULT '',
    registration_deadline TEXT NOT NULL,
    event_start_date TEXT NOT NULL,
    event_end_date TEXT NOT NULL,
    registration_url TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Open',
    bookmarked BOOLEAN DEFAULT false,
    platform TEXT,
    platform_name TEXT,
    source TEXT DEFAULT '',
    discovered_at TIMESTAMPTZ,
    prize_pool TEXT,
    event_type TEXT,
    is_new BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Scraper Sources Table
CREATE TABLE IF NOT EXISTS public.scraper_sources (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'hackathon',
    color TEXT DEFAULT '#0086bf',
    status TEXT DEFAULT 'active',
    last_scraped_at TIMESTAMPTZ,
    items_found INTEGER DEFAULT 0,
    enabled BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Crawler Logs Table
CREATE TABLE IF NOT EXISTS public.crawler_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TEXT NOT NULL,
    text TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'info',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. High Performance PostgreSQL Indexes
CREATE INDEX IF NOT EXISTS idx_hackathons_category ON public.hackathons (category);
CREATE INDEX IF NOT EXISTS idx_hackathons_mode ON public.hackathons (mode);
CREATE INDEX IF NOT EXISTS idx_hackathons_status ON public.hackathons (status);
CREATE INDEX IF NOT EXISTS idx_hackathons_type ON public.hackathons (type);
CREATE INDEX IF NOT EXISTS idx_hackathons_platform ON public.hackathons (platform);
CREATE INDEX IF NOT EXISTS idx_hackathons_deadline ON public.hackathons (registration_deadline);
CREATE INDEX IF NOT EXISTS idx_hackathons_bookmarked ON public.hackathons (bookmarked);
CREATE INDEX IF NOT EXISTS idx_scraper_sources_type ON public.scraper_sources (type);
CREATE INDEX IF NOT EXISTS idx_crawler_logs_created ON public.crawler_logs (created_at DESC);

-- 6. Trigger to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS on_hackathons_updated ON public.hackathons;
CREATE TRIGGER on_hackathons_updated
    BEFORE UPDATE ON public.hackathons
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- 7. Configure Row Level Security (RLS)
ALTER TABLE public.hackathons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scraper_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crawler_logs ENABLE ROW LEVEL SECURITY;

-- Allow anonymous & authenticated users full access for demo/single-tenant tracker
DROP POLICY IF EXISTS "Allow public read hackathons" ON public.hackathons;
CREATE POLICY "Allow public read hackathons" ON public.hackathons
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert hackathons" ON public.hackathons;
CREATE POLICY "Allow public insert hackathons" ON public.hackathons
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update hackathons" ON public.hackathons;
CREATE POLICY "Allow public update hackathons" ON public.hackathons
    FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete hackathons" ON public.hackathons;
CREATE POLICY "Allow public delete hackathons" ON public.hackathons
    FOR DELETE USING (true);

-- Scraper Sources RLS
DROP POLICY IF EXISTS "Allow public read scraper_sources" ON public.scraper_sources;
CREATE POLICY "Allow public read scraper_sources" ON public.scraper_sources
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public write scraper_sources" ON public.scraper_sources;
CREATE POLICY "Allow public write scraper_sources" ON public.scraper_sources
    FOR ALL USING (true);

-- Crawler Logs RLS
DROP POLICY IF EXISTS "Allow public read crawler_logs" ON public.crawler_logs;
CREATE POLICY "Allow public read crawler_logs" ON public.crawler_logs
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public write crawler_logs" ON public.crawler_logs;
CREATE POLICY "Allow public write crawler_logs" ON public.crawler_logs
    FOR ALL USING (true);

-- 8. Seed Initial Real-World Hackathons & Tech Events (Upsert)
INSERT INTO public.hackathons (
    id, title, type, description, organizer, category, mode,
    location, city, country, registration_deadline, event_start_date,
    event_end_date, registration_url, status, bookmarked,
    platform, platform_name, source, prize_pool, is_new
) VALUES
(
    'hack-1',
    'Global AI & Autonomous Agents Hackathon 2026',
    'hackathon',
    'Build cutting-edge multi-agent systems, generative AI applications, and autonomous workflows solving real-world enterprise problems.',
    'DeepTech AI Alliance (Devpost)',
    'AI/ML',
    'Online',
    'Online (Global)',
    'Online',
    'Global',
    '2026-10-25',
    '2026-11-01',
    '2026-11-03',
    'https://devpost.com/hackathons/global-ai-agents-2026',
    'Registered',
    true,
    'devpost',
    'Devpost',
    'Devpost Community Feed',
    '$50,000',
    false
),
(
    'hack-2',
    'NextGen Web3 & Zero-Knowledge Summit',
    'hackathon',
    'Design decentralized dApps, zero-knowledge privacy layers, and cross-chain interoperability protocols.',
    'Ethereum Developers Guild (Devfolio)',
    'Blockchain',
    'Hybrid',
    'San Francisco, CA, USA & Online',
    'San Francisco',
    'USA',
    '2026-10-18',
    '2026-10-24',
    '2026-10-26',
    'https://devfolio.co/hackathons/web3-zk-summit-2026',
    'Not Registered',
    false,
    'devfolio',
    'Devfolio',
    'Devfolio Web3 Radar',
    '$75,000',
    false
),
(
    'hack-3',
    'Fullstack Cloud & Microservices Sprint',
    'hackathon',
    'Create scalable cloud-native architectures, real-time reactive platforms, and high-performance serverless services.',
    'CloudNative Collective (HackerEarth)',
    'Web Development',
    'Online',
    'Online (Global)',
    'Online',
    'Global',
    '2026-10-12',
    '2026-10-15',
    '2026-10-17',
    'https://www.hackerearth.com/challenges/hackathon/cloud-microservices-sprint-2026',
    'Participating',
    true,
    'hackerearth',
    'HackerEarth',
    'HackerEarth Enterprise Stream',
    '$30,000',
    false
),
(
    'hack-4',
    'Smart Hardware & Edge IoT Innovators',
    'hackathon',
    'Prototype embedded systems, robotics sensors, and smart city automation with edge AI processing.',
    'RoboTech Institute (Unstop)',
    'IoT',
    'Offline',
    'Austin, Texas, USA',
    'Austin',
    'USA',
    '2026-11-05',
    '2026-11-14',
    '2026-11-16',
    'https://unstop.com/hackathons/smart-edge-iot-innovators-2026',
    'Not Registered',
    false,
    'unstop',
    'Unstop',
    'Unstop Campus Stream',
    '$25,000',
    false
),
(
    'hack-5',
    'CyberShield CTF & Defense Challenge',
    'hackathon',
    'Test application security boundaries, patch zero-day vulnerabilities, and construct defensive cryptographic primitives.',
    'InfoSec Alliance (Hack2Skill)',
    'Cybersecurity',
    'Online',
    'Online (Global)',
    'Online',
    'India',
    '2026-09-20',
    '2026-09-25',
    '2026-09-27',
    'https://hack2skill.com/challenges/cybershield-defense-2026',
    'Completed',
    false,
    'hack2skill',
    'Hack2Skill',
    'Hack2Skill Cyber Hub',
    '₹1,500,000',
    false
),
(
    'hack-6',
    'Cross-Platform Mobile App Jam',
    'hackathon',
    'Build intuitive, fluid, and offline-first mobile experiences for iOS and Android using modern frameworks.',
    'MobileDev United (BeMyApp)',
    'Mobile Development',
    'Hybrid',
    'Berlin, Germany & Online',
    'Berlin',
    'Germany',
    '2026-11-20',
    '2026-11-28',
    '2026-11-30',
    'https://bemyapp.com/events/cross-platform-mobile-app-jam',
    'Not Registered',
    true,
    'bemyapp',
    'BeMyApp',
    'BeMyApp European Network',
    '€35,000',
    false
),
(
    'hack-7',
    'Open Innovation & ClimateTech Challenge',
    'hackathon',
    'Collaborate on open-source solutions tackling carbon accounting, renewable energy distribution, and sustainability.',
    'GreenTech Open Lab (HeroX)',
    'Open Innovation',
    'Online',
    'Online (Global)',
    'Online',
    'Global',
    '2026-10-30',
    '2026-11-08',
    '2026-11-10',
    'https://www.herox.com/climatetech-open-innovation-challenge',
    'Not Registered',
    false,
    'herox',
    'HeroX',
    'HeroX Crowdsource Portal',
    '$100,000',
    false
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    organizer = EXCLUDED.organizer,
    category = EXCLUDED.category,
    mode = EXCLUDED.mode,
    location = EXCLUDED.location,
    city = EXCLUDED.city,
    country = EXCLUDED.country,
    registration_deadline = EXCLUDED.registration_deadline,
    event_start_date = EXCLUDED.event_start_date,
    event_end_date = EXCLUDED.event_end_date,
    registration_url = EXCLUDED.registration_url,
    status = EXCLUDED.status,
    bookmarked = EXCLUDED.bookmarked,
    platform = EXCLUDED.platform,
    platform_name = EXCLUDED.platform_name,
    source = EXCLUDED.source,
    prize_pool = EXCLUDED.prize_pool,
    updated_at = NOW();

-- 9. Seed 22 Discovery Platforms (11 Hackathon + 11 Tech Event)
INSERT INTO public.scraper_sources (id, name, url, type, color, status, enabled) VALUES
-- Hackathon Platforms
('devpost', 'Devpost', 'https://devpost.com/hackathons', 'hackathon', '#0086bf', 'active', true),
('devfolio', 'Devfolio', 'https://devfolio.co/hackathons', 'hackathon', '#3770ff', 'active', true),
('hackerearth', 'HackerEarth', 'https://www.hackerearth.com/challenges/hackathon/', 'hackathon', '#2ec4b6', 'active', true),
('unstop', 'Unstop', 'https://unstop.com/hackathons', 'hackathon', '#1c4980', 'active', true),
('reskill', 'Reskilll', 'https://reskilll.com/hackathons', 'hackathon', '#ff5722', 'active', true),
('hack2skill', 'Hack2Skill', 'https://hack2skill.com/challenges', 'hackathon', '#6c5ce7', 'active', true),
('mlh', 'Major League Hacking (MLH)', 'https://mlh.io/seasons/2026/events', 'hackathon', '#e73427', 'active', true),
('herox', 'HeroX', 'https://www.herox.com/crowdsourcing-projects', 'hackathon', '#ff7043', 'active', true),
('brightidea', 'Brightidea', 'https://www.brightidea.com/innovation-challenges', 'hackathon', '#00c853', 'active', true),
('bemyapp', 'BeMyApp', 'https://bemyapp.com/events', 'hackathon', '#e91e63', 'active', true),
('stackup', 'StackUp', 'https://stackup.dev/campaigns', 'hackathon', '#673ab7', 'active', true),
-- Tech Event & Community Platforms
('jamao', 'Jamao', 'https://jamao.in/events', 'event', '#f59e0b', 'active', true),
('luma', 'Luma (lu.ma)', 'https://lu.ma/explore/tech', 'event', '#ec4899', 'active', true),
('eventbrite', 'Eventbrite', 'https://www.eventbrite.com/d/online/tech-events/', 'event', '#f97316', 'active', true),
('allevents', 'AllEvents', 'https://allevents.in/online/technology', 'event', '#06b6d4', 'active', true),
('maidan', 'Maidan', 'https://maidan.app/tech-summits', 'event', '#10b981', 'active', true),
('techmeetups', 'TechMeetups', 'https://techmeetups.com/events', 'event', '#3b82f6', 'active', true),
('startupmelas', 'StartupMelas', 'https://startupmelas.com/gatherings', 'event', '#8b5cf6', 'active', true),
('eventindia', 'EventIndia', 'https://eventindia.in/conferences', 'event', '#ef4444', 'active', true),
('gdg-chennai', 'GDG Chennai', 'https://gdg.community.dev/gdg-chennai/', 'event', '#4285f4', 'active', true),
('devfest-chennai', 'DevFest Chennai', 'https://devfestchennai.com', 'event', '#ea4335', 'active', true),
('bengaluru-tech-week', 'Bengaluru Tech Week', 'https://bengalurutechweek.com', 'event', '#14b8a6', 'active', true)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    url = EXCLUDED.url,
    type = EXCLUDED.type,
    color = EXCLUDED.color,
    status = EXCLUDED.status,
    enabled = EXCLUDED.enabled;
